#!/usr/bin/env tsx
import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';

const COLORS = {
  reset: '\x1b[0m',
  green: '\x1b[32m',
  red: '\x1b[31m',
  yellow: '\x1b[33m',
  blue: '\x1b[34m',
};

function log(message: string, color: string = COLORS.reset) {
  console.log(`${color}${message}${COLORS.reset}`);
}

interface QueryInfo {
  name: string;
  query: string;
  variables: string[];
  fields: string[];
}

function extractQueries(filePath: string): QueryInfo[] {
  const content = fs.readFileSync(filePath, 'utf-8');
  const queryRegex = /export const (\w+_QUERY)(?:\s*=\s*\([^)]*\))?\s*=\s*gql\(`([^`]+)`/g;
  const queries: QueryInfo[] = [];
  
  let match;
  while ((match = queryRegex.exec(content)) !== null) {
    const [_, name, queryContent] = match;
    
    // Extrahiere Variablen
    const varRegex = /\$(\w+)/g;
    const variables = new Set<string>();
    let varMatch;
    while ((varMatch = varRegex.exec(queryContent)) !== null) {
      variables.add(varMatch[1]);
    }
    
    // Extrahiere Felder (einfache Version)
    const fieldRegex = /\b(\w+)(?=\s*[{\s])/g;
    const fields = new Set<string>();
    let fieldMatch;
    while ((fieldMatch = fieldRegex.exec(queryContent)) !== null) {
      if (!['query', 'mutation', 'subscription', 'first', 'skip', 'orderBy', 'orderDirection'].includes(fieldMatch[1])) {
        fields.add(fieldMatch[1]);
      }
    }
    
    queries.push({
      name,
      query: queryContent.trim(),
      variables: Array.from(variables),
      fields: Array.from(fields),
    });
  }
  
  return queries;
}

function generateTypeForQuery(query: QueryInfo): string {
  const typeName = query.name.replace('_QUERY', 'Result');
  
  return `
export interface ${typeName} {
  data: {
    ${query.fields.map(f => `  ${f}: any;`).join('\n    ')}
  };
  errors?: Array<{
    message: string;
    locations?: Array<{ line: number; column: number }>;
  }>;
}`;
}

function main() {
  log('\n🔧 STARTE QUERY-GENERIERUNG\n', COLORS.blue);

  // 1. Lade Queries
  const queriesPath = 'src/lib/queries.ts';
  if (!fs.existsSync(queriesPath)) {
    log(`❌ queries.ts nicht gefunden unter ${queriesPath}`, COLORS.red);
    process.exit(1);
  }

  const queries = extractQueries(queriesPath);
  log(`📚 Gefundene Queries: ${queries.length}`, COLORS.green);
  
  // 2. Erstelle generated Ordner
  const generatedDir = 'src/types/generated';
  if (!fs.existsSync(generatedDir)) {
    fs.mkdirSync(generatedDir, { recursive: true });
    log(`📁 Erstelle Verzeichnis: ${generatedDir}`, COLORS.green);
  }

  // 3. Generiere Typ-Dateien
  const generatedTypes: string[] = [];
  const indexImports: string[] = [];

  queries.forEach(query => {
    const typeName = query.name.replace('_QUERY', 'Result');
    const fileName = `${query.name.toLowerCase()}.ts`;
    const filePath = path.join(generatedDir, fileName);
    
    const content = `// Autogenerated from ${query.name}
export interface ${typeName} {
  data: {
    ${query.fields.map(f => `  ${f}: any;`).join('\n    ')}
  };
  errors?: Array<{
    message: string;
    locations?: Array<{ line: number; column: number }>;
  }>;
}

// Query Info
export const ${query.name}_INFO = {
  name: '${query.name}',
  variables: ${JSON.stringify(query.variables, null, 2)},
  fields: ${JSON.stringify(query.fields, null, 2)},
};
`;
    
    fs.writeFileSync(filePath, content);
    generatedTypes.push(filePath);
    indexImports.push(`export * from './${fileName.replace('.ts', '')}';`);
    
    log(`   ✅ ${query.name} -> ${fileName}`, COLORS.green);
  });

  // 4. Erstelle Index-Datei
  const indexPath = path.join(generatedDir, 'index.ts');
  fs.writeFileSync(indexPath, indexImports.join('\n'));
  log(`\n📦 Generierte Typen in ${indexPath}`, COLORS.green);

  // 5. Erstelle Query-Validator
  const validatorPath = path.join(generatedDir, 'query-validator.ts');
  const validatorContent = `// Autogenerated Query Validator
import { queries } from './queries';

export function validateQuery(queryName: string, variables: Record<string, any>): boolean {
  const queryInfo = (queries as any)[queryName + '_INFO'];
  if (!queryInfo) return false;
  
  // Prüfe ob alle benötigten Variablen vorhanden sind
  return queryInfo.variables.every((v: string) => variables[v] !== undefined);
}

export const queries = {
${queries.map(q => `  ${q.name}_INFO,`).join('\n')}
};
`;
  
  fs.writeFileSync(validatorPath, validatorContent);
  log(`📦 Generierte Query-Validator in ${validatorPath}`, COLORS.green);

  // 6. Zusammenfassung
  log('\n📊 ZUSAMMENFASSUNG', COLORS.blue);
  log('────────────────', COLORS.blue);
  
  log(`✨ ${generatedTypes.length} Typ-Dateien generiert`, COLORS.green);
  log(`   in ${generatedDir}`, COLORS.green);
  
  log('\n📝 Nächste Schritte:', COLORS.blue);
  log('   1. Führe `npm run codegen` aus für GraphQL-Typen', COLORS.yellow);
  log('   2. Führe `npm run validate` aus zur Prüfung', COLORS.yellow);
  log('   3. Führe `npm run build` aus', COLORS.yellow);
}

// Am Ende der Datei:
if (import.meta.url === `file://${process.argv[1]}`) {
  main();
}